nelmio_api_doc:
    documentation:
        info:
            title: NEXA API
            description: API documentation for Tasks and related services.
            version: 1.0.0
        components:
            securitySchemes:
                Bearer:
                    type: http
                    scheme: bearer
                    bearerFormat: JWT
        security:
            - Bearer: []
    areas:
        default:
            path_patterns:
                - ^/api(?!/doc$)
