<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUVHam0f\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUVHam0f/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUVHam0f.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUVHam0f\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUVHam0f\App_KernelDevDebugContainer([
    'container.build_hash' => 'UVHam0f',
    'container.build_id' => 'b9d3d05d',
    'container.build_time' => 1771633571,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUVHam0f');
