<?php

namespace ContainerRUkMl8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMouvement2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.E5IpTQe.App\Entity\Mouvement' shared service.
     *
     * @return \App\Entity\Mouvement
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.E5IpTQe": it needs an instance of "App\\Entity\\Mouvement" but this type has been excluded in "config/services.yaml".');
    }
}
