<?php

namespace ContainerRUkMl8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0sC8x64Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0sC8x64' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0sC8x64'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mouvement' => ['privates', '.errored..service_locator.0sC8x64.App\\Entity\\Mouvement', NULL, 'Cannot autowire service ".service_locator.0sC8x64": it needs an instance of "App\\Entity\\Mouvement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'mouvement' => 'App\\Entity\\Mouvement',
        ]);
    }
}
