<?php

namespace ContainerRUkMl8x;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C35RGENService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.c35RGEN' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.c35RGEN'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'App\\Controller\\Admin\\AdminMouvementController::index' => ['privates', '.service_locator.P6CGvh6', 'get_ServiceLocator_P6CGvh6Service', true],
            'App\\Controller\\Admin\\AdminProduitController::index' => ['privates', '.service_locator.1e6N2H_', 'get_ServiceLocator_1e6N2HService', true],
            'App\\Controller\\MouvementController::delete' => ['privates', '.service_locator.E5IpTQe', 'get_ServiceLocator_E5IpTQeService', true],
            'App\\Controller\\MouvementController::edit' => ['privates', '.service_locator.E5IpTQe', 'get_ServiceLocator_E5IpTQeService', true],
            'App\\Controller\\MouvementController::index' => ['privates', '.service_locator.HgulY7s', 'get_ServiceLocator_HgulY7sService', true],
            'App\\Controller\\MouvementController::new' => ['privates', '.service_locator.dBX4G6u', 'get_ServiceLocator_DBX4G6uService', true],
            'App\\Controller\\MouvementController::pdf' => ['privates', '.service_locator.HgulY7s', 'get_ServiceLocator_HgulY7sService', true],
            'App\\Controller\\MouvementController::show' => ['privates', '.service_locator.0sC8x64', 'get_ServiceLocator_0sC8x64Service', true],
            'App\\Controller\\MouvementController::stats' => ['privates', '.service_locator.P6CGvh6', 'get_ServiceLocator_P6CGvh6Service', true],
            'App\\Controller\\ProduitController::delete' => ['privates', '.service_locator.6DpIc9s', 'get_ServiceLocator_6DpIc9sService', true],
            'App\\Controller\\ProduitController::edit' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\ProduitController::index' => ['privates', '.service_locator.1e6N2H_', 'get_ServiceLocator_1e6N2HService', true],
            'App\\Controller\\ProduitController::new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProduitController::pdf' => ['privates', '.service_locator.1e6N2H_', 'get_ServiceLocator_1e6N2HService', true],
            'App\\Controller\\ProduitController::show' => ['privates', '.service_locator.b2NFX8Z', 'get_ServiceLocator_B2NFX8ZService', true],
            'App\\Controller\\ProduitController::stats' => ['privates', '.service_locator.1e6N2H_', 'get_ServiceLocator_1e6N2HService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'App\\Controller\\Admin\\AdminMouvementController:index' => ['privates', '.service_locator.P6CGvh6', 'get_ServiceLocator_P6CGvh6Service', true],
            'App\\Controller\\Admin\\AdminProduitController:index' => ['privates', '.service_locator.1e6N2H_', 'get_ServiceLocator_1e6N2HService', true],
            'App\\Controller\\MouvementController:delete' => ['privates', '.service_locator.E5IpTQe', 'get_ServiceLocator_E5IpTQeService', true],
            'App\\Controller\\MouvementController:edit' => ['privates', '.service_locator.E5IpTQe', 'get_ServiceLocator_E5IpTQeService', true],
            'App\\Controller\\MouvementController:index' => ['privates', '.service_locator.HgulY7s', 'get_ServiceLocator_HgulY7sService', true],
            'App\\Controller\\MouvementController:new' => ['privates', '.service_locator.dBX4G6u', 'get_ServiceLocator_DBX4G6uService', true],
            'App\\Controller\\MouvementController:pdf' => ['privates', '.service_locator.HgulY7s', 'get_ServiceLocator_HgulY7sService', true],
            'App\\Controller\\MouvementController:show' => ['privates', '.service_locator.0sC8x64', 'get_ServiceLocator_0sC8x64Service', true],
            'App\\Controller\\MouvementController:stats' => ['privates', '.service_locator.P6CGvh6', 'get_ServiceLocator_P6CGvh6Service', true],
            'App\\Controller\\ProduitController:delete' => ['privates', '.service_locator.6DpIc9s', 'get_ServiceLocator_6DpIc9sService', true],
            'App\\Controller\\ProduitController:edit' => ['privates', '.service_locator.Gl3nBvd', 'get_ServiceLocator_Gl3nBvdService', true],
            'App\\Controller\\ProduitController:index' => ['privates', '.service_locator.1e6N2H_', 'get_ServiceLocator_1e6N2HService', true],
            'App\\Controller\\ProduitController:new' => ['privates', '.service_locator.9kKwU2t', 'get_ServiceLocator_9kKwU2tService', true],
            'App\\Controller\\ProduitController:pdf' => ['privates', '.service_locator.1e6N2H_', 'get_ServiceLocator_1e6N2HService', true],
            'App\\Controller\\ProduitController:show' => ['privates', '.service_locator.b2NFX8Z', 'get_ServiceLocator_B2NFX8ZService', true],
            'App\\Controller\\ProduitController:stats' => ['privates', '.service_locator.1e6N2H_', 'get_ServiceLocator_1e6N2HService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.y4_Zrx.', 'get_ServiceLocator_Y4Zrx_Service', true],
        ], [
            'App\\Controller\\Admin\\AdminMouvementController::index' => '?',
            'App\\Controller\\Admin\\AdminProduitController::index' => '?',
            'App\\Controller\\MouvementController::delete' => '?',
            'App\\Controller\\MouvementController::edit' => '?',
            'App\\Controller\\MouvementController::index' => '?',
            'App\\Controller\\MouvementController::new' => '?',
            'App\\Controller\\MouvementController::pdf' => '?',
            'App\\Controller\\MouvementController::show' => '?',
            'App\\Controller\\MouvementController::stats' => '?',
            'App\\Controller\\ProduitController::delete' => '?',
            'App\\Controller\\ProduitController::edit' => '?',
            'App\\Controller\\ProduitController::index' => '?',
            'App\\Controller\\ProduitController::new' => '?',
            'App\\Controller\\ProduitController::pdf' => '?',
            'App\\Controller\\ProduitController::show' => '?',
            'App\\Controller\\ProduitController::stats' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'App\\Controller\\Admin\\AdminMouvementController:index' => '?',
            'App\\Controller\\Admin\\AdminProduitController:index' => '?',
            'App\\Controller\\MouvementController:delete' => '?',
            'App\\Controller\\MouvementController:edit' => '?',
            'App\\Controller\\MouvementController:index' => '?',
            'App\\Controller\\MouvementController:new' => '?',
            'App\\Controller\\MouvementController:pdf' => '?',
            'App\\Controller\\MouvementController:show' => '?',
            'App\\Controller\\MouvementController:stats' => '?',
            'App\\Controller\\ProduitController:delete' => '?',
            'App\\Controller\\ProduitController:edit' => '?',
            'App\\Controller\\ProduitController:index' => '?',
            'App\\Controller\\ProduitController:new' => '?',
            'App\\Controller\\ProduitController:pdf' => '?',
            'App\\Controller\\ProduitController:show' => '?',
            'App\\Controller\\ProduitController:stats' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
        ]);
    }
}
