<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NQLmHgVService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NQLmHgV' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NQLmHgV'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'themeRepository' => ['privates', 'App\\Repository\\ThemeRepository', 'getThemeRepositoryService', true],
        ], [
            'themeRepository' => 'App\\Repository\\ThemeRepository',
        ]);
    }
}
