<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_O7u4FJ3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.o7u4FJ3' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.o7u4FJ3'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'phoenixGoal' => ['privates', '.errored..service_locator.o7u4FJ3.App\\Entity\\PhoenixGoal', NULL, 'Cannot autowire service ".service_locator.o7u4FJ3": it needs an instance of "App\\Entity\\PhoenixGoal" but this type has been excluded in "config/services.yaml".'],
        ], [
            'phoenixGoal' => 'App\\Entity\\PhoenixGoal',
        ]);
    }
}
