<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HgulY7sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.HgulY7s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.HgulY7s'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'produitRepository' => ['privates', 'App\\Repository\\ProduitRepository', 'getProduitRepositoryService', true],
            'repo' => ['privates', 'App\\Repository\\MouvementRepository', 'getMouvementRepositoryService', true],
        ], [
            'produitRepository' => 'App\\Repository\\ProduitRepository',
            'repo' => 'App\\Repository\\MouvementRepository',
        ]);
    }
}
