<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TkpwMyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._tkpwMy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._tkpwMy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'executionRepository' => ['privates', 'App\\Repository\\ExecutionRepository', 'getExecutionRepositoryService', true],
            'taskRepository' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'executionRepository' => 'App\\Repository\\ExecutionRepository',
            'taskRepository' => 'App\\Repository\\TaskRepository',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
