<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0B1GGZgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0B1GGZg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0B1GGZg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'goalRepository' => ['privates', 'App\\Repository\\GoalRepository', 'getGoalRepositoryService', true],
            'messagesService' => ['privates', 'App\\Service\\MotivationMessagesService', 'getMotivationMessagesServiceService', true],
            'moodClickRepository' => ['privates', 'App\\Repository\\MoodClickRepository', 'getMoodClickRepositoryService', true],
            'motivationRepository' => ['privates', 'App\\Repository\\MotivationRepository', 'getMotivationRepositoryService', true],
        ], [
            'goalRepository' => 'App\\Repository\\GoalRepository',
            'messagesService' => 'App\\Service\\MotivationMessagesService',
            'moodClickRepository' => 'App\\Repository\\MoodClickRepository',
            'motivationRepository' => 'App\\Repository\\MotivationRepository',
        ]);
    }
}
