<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T_UPThhService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T.UPThh' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T.UPThh'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'questionRepository' => ['privates', 'App\\Repository\\QuestionRepository', 'getQuestionRepositoryService', true],
            'theme' => ['privates', '.errored..service_locator.T.UPThh.App\\Entity\\Theme', NULL, 'Cannot autowire service ".service_locator.T.UPThh": it needs an instance of "App\\Entity\\Theme" but this type has been excluded in "config/services.yaml".'],
        ], [
            'questionRepository' => 'App\\Repository\\QuestionRepository',
            'theme' => 'App\\Entity\\Theme',
        ]);
    }
}
