<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Gl3nBvdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Gl3nBvd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'produit' => ['privates', '.errored..service_locator.Gl3nBvd.App\\Entity\\Produit', NULL, 'Cannot autowire service ".service_locator.Gl3nBvd": it needs an instance of "App\\Entity\\Produit" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'produit' => 'App\\Entity\\Produit',
        ]);

        if (isset($container->privates['.service_locator.Gl3nBvd'])) {
            return $container->privates['.service_locator.Gl3nBvd'];
        }

        return $container->privates['.service_locator.Gl3nBvd'] = $instance;
    }
}
