<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KHhLsD9Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.kHhLsD9' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.kHhLsD9'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'motivation' => ['privates', '.errored..service_locator.kHhLsD9.App\\Entity\\Motivation', NULL, 'Cannot autowire service ".service_locator.kHhLsD9": it needs an instance of "App\\Entity\\Motivation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'motivation' => 'App\\Entity\\Motivation',
        ]);
    }
}
