<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__ZPZ1OjService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator..ZPZ1Oj' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'repo' => ['privates', 'App\\Repository\\ExecutionRepository', 'getExecutionRepositoryService', true],
        ], [
            'em' => '?',
            'repo' => 'App\\Repository\\ExecutionRepository',
        ]);

        if (isset($container->privates['.service_locator..ZPZ1Oj'])) {
            return $container->privates['.service_locator..ZPZ1Oj'];
        }

        return $container->privates['.service_locator..ZPZ1Oj'] = $instance;
    }
}
