<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X2wPFdAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.x2wPFdA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.x2wPFdA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'repository' => ['privates', 'App\\Repository\\TimeMessageRepository', 'getTimeMessageRepositoryService', true],
            'timeMessage' => ['privates', '.errored..service_locator.x2wPFdA.App\\Entity\\TimeMessage', NULL, 'Cannot autowire service ".service_locator.x2wPFdA": it needs an instance of "App\\Entity\\TimeMessage" but this type has been excluded in "config/services.yaml".'],
        ], [
            'repository' => 'App\\Repository\\TimeMessageRepository',
            'timeMessage' => 'App\\Entity\\TimeMessage',
        ]);
    }
}
