<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_93WRVlAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.93WRVlA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'phoenixService' => ['privates', 'App\\Service\\PhoenixService', 'getPhoenixServiceService', true],
        ], [
            'entityManager' => '?',
            'phoenixService' => 'App\\Service\\PhoenixService',
        ]);

        if (isset($container->privates['.service_locator.93WRVlA'])) {
            return $container->privates['.service_locator.93WRVlA'];
        }

        return $container->privates['.service_locator.93WRVlA'] = $instance;
    }
}
