<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8RKRJTService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8RKRJ_T' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.8RKRJ_T'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'categoryRepo' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'executionRepo' => ['privates', 'App\\Repository\\ExecutionRepository', 'getExecutionRepositoryService', true],
            'taskRepo' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
            'userRepo' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'categoryRepo' => 'App\\Repository\\CategoryRepository',
            'executionRepo' => 'App\\Repository\\ExecutionRepository',
            'taskRepo' => 'App\\Repository\\TaskRepository',
            'userRepo' => 'App\\Repository\\UserRepository',
        ]);
    }
}
