<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VZgwsZdService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.VZgwsZd' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.VZgwsZd'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'phoenixNetwork' => ['privates', '.errored..service_locator.VZgwsZd.App\\Entity\\PhoenixNetwork', NULL, 'Cannot autowire service ".service_locator.VZgwsZd": it needs an instance of "App\\Entity\\PhoenixNetwork" but this type has been excluded in "config/services.yaml".'],
        ], [
            'phoenixNetwork' => 'App\\Entity\\PhoenixNetwork',
        ]);
    }
}
