<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4HlxbTbService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4HlxbTb' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'catRepo' => ['privates', 'App\\Repository\\CategoryRepository', 'getCategoryRepositoryService', true],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'task' => ['privates', '.errored..service_locator.4HlxbTb.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.4HlxbTb": it needs an instance of "App\\Entity\\Task" but this type has been excluded in "config/services.yaml".'],
            'validator' => ['privates', 'debug.validator', 'getDebug_ValidatorService', false],
        ], [
            'catRepo' => 'App\\Repository\\CategoryRepository',
            'em' => '?',
            'task' => 'App\\Entity\\Task',
            'validator' => '?',
        ]);

        if (isset($container->privates['.service_locator.4HlxbTb'])) {
            return $container->privates['.service_locator.4HlxbTb'];
        }

        return $container->privates['.service_locator.4HlxbTb'] = $instance;
    }
}
