<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_D1Ap5XlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.d1Ap5Xl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'phoenixNetwork' => ['privates', '.errored..service_locator.d1Ap5Xl.App\\Entity\\PhoenixNetwork', NULL, 'Cannot autowire service ".service_locator.d1Ap5Xl": it needs an instance of "App\\Entity\\PhoenixNetwork" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'phoenixNetwork' => 'App\\Entity\\PhoenixNetwork',
        ]);

        if (isset($container->privates['.service_locator.d1Ap5Xl'])) {
            return $container->privates['.service_locator.d1Ap5Xl'];
        }

        return $container->privates['.service_locator.d1Ap5Xl'] = $instance;
    }
}
