<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C2H9aP6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C2H9aP6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C2H9aP6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'phoenixWisdomRepository' => ['privates', 'App\\Repository\\PhoenixWisdomRepository', 'getPhoenixWisdomRepositoryService', true],
        ], [
            'phoenixWisdomRepository' => 'App\\Repository\\PhoenixWisdomRepository',
        ]);
    }
}
