<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GKPBAx1Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.gKPBAx1' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'category' => ['privates', '.errored..service_locator.gKPBAx1.App\\Entity\\Category', NULL, 'Cannot autowire service ".service_locator.gKPBAx1": it needs an instance of "App\\Entity\\Category" but this type has been excluded in "config/services.yaml".'],
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
        ], [
            'category' => 'App\\Entity\\Category',
            'em' => '?',
        ]);

        if (isset($container->privates['.service_locator.gKPBAx1'])) {
            return $container->privates['.service_locator.gKPBAx1'];
        }

        return $container->privates['.service_locator.gKPBAx1'] = $instance;
    }
}
