<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KWHzXlService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._KWHzXl' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'phoenixGoal' => ['privates', '.errored..service_locator._KWHzXl.App\\Entity\\PhoenixGoal', NULL, 'Cannot autowire service ".service_locator._KWHzXl": it needs an instance of "App\\Entity\\PhoenixGoal" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'phoenixGoal' => 'App\\Entity\\PhoenixGoal',
        ]);

        if (isset($container->privates['.service_locator._KWHzXl'])) {
            return $container->privates['.service_locator._KWHzXl'];
        }

        return $container->privates['.service_locator._KWHzXl'] = $instance;
    }
}
