<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8ksJNcQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.8ksJNcQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'question' => ['privates', '.errored..service_locator.8ksJNcQ.App\\Entity\\Question', NULL, 'Cannot autowire service ".service_locator.8ksJNcQ": it needs an instance of "App\\Entity\\Question" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'question' => 'App\\Entity\\Question',
        ]);

        if (isset($container->privates['.service_locator.8ksJNcQ'])) {
            return $container->privates['.service_locator.8ksJNcQ'];
        }

        return $container->privates['.service_locator.8ksJNcQ'] = $instance;
    }
}
