<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B2NFX8ZService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.b2NFX8Z' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.b2NFX8Z'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'mouvementRepository' => ['privates', 'App\\Repository\\MouvementRepository', 'getMouvementRepositoryService', true],
            'produit' => ['privates', '.errored..service_locator.b2NFX8Z.App\\Entity\\Produit', NULL, 'Cannot autowire service ".service_locator.b2NFX8Z": it needs an instance of "App\\Entity\\Produit" but this type has been excluded in "config/services.yaml".'],
        ], [
            'mouvementRepository' => 'App\\Repository\\MouvementRepository',
            'produit' => 'App\\Entity\\Produit',
        ]);
    }
}
