<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E5IpTQeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.E5IpTQe' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'mouvement' => ['privates', '.errored..service_locator.E5IpTQe.App\\Entity\\Mouvement', NULL, 'Cannot autowire service ".service_locator.E5IpTQe": it needs an instance of "App\\Entity\\Mouvement" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'mouvement' => 'App\\Entity\\Mouvement',
        ]);

        if (isset($container->privates['.service_locator.E5IpTQe'])) {
            return $container->privates['.service_locator.E5IpTQe'];
        }

        return $container->privates['.service_locator.E5IpTQe'] = $instance;
    }
}
