<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_BlHuOkaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.blHuOka' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'taskRepo' => ['privates', 'App\\Repository\\TaskRepository', 'getTaskRepositoryService', true],
        ], [
            'em' => '?',
            'taskRepo' => 'App\\Repository\\TaskRepository',
        ]);

        if (isset($container->privates['.service_locator.blHuOka'])) {
            return $container->privates['.service_locator.blHuOka'];
        }

        return $container->privates['.service_locator.blHuOka'] = $instance;
    }
}
