<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_TWq7s9mService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.tWq7s9m' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.tWq7s9m'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'phoenixNetworkRepository' => ['privates', 'App\\Repository\\PhoenixNetworkRepository', 'getPhoenixNetworkRepositoryService', true],
        ], [
            'phoenixNetworkRepository' => 'App\\Repository\\PhoenixNetworkRepository',
        ]);
    }
}
