<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_ZG89c6xService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.ZG89c6x' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'theme' => ['privates', '.errored..service_locator.ZG89c6x.App\\Entity\\Theme', NULL, 'Cannot autowire service ".service_locator.ZG89c6x": it needs an instance of "App\\Entity\\Theme" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'theme' => 'App\\Entity\\Theme',
        ]);

        if (isset($container->privates['.service_locator.ZG89c6x'])) {
            return $container->privates['.service_locator.ZG89c6x'];
        }

        return $container->privates['.service_locator.ZG89c6x'] = $instance;
    }
}
