<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HqQD9t0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hqQD9t0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'phoenixWisdom' => ['privates', '.errored..service_locator.hqQD9t0.App\\Entity\\PhoenixWisdom', NULL, 'Cannot autowire service ".service_locator.hqQD9t0": it needs an instance of "App\\Entity\\PhoenixWisdom" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'phoenixWisdom' => 'App\\Entity\\PhoenixWisdom',
        ]);

        if (isset($container->privates['.service_locator.hqQD9t0'])) {
            return $container->privates['.service_locator.hqQD9t0'];
        }

        return $container->privates['.service_locator.hqQD9t0'] = $instance;
    }
}
