<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_B11qcrPService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.B11qcrP' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'milestonesRepository' => ['privates', 'App\\Repository\\MilestonesRepository', 'getMilestonesRepositoryService', true],
        ], [
            'entityManager' => '?',
            'milestonesRepository' => 'App\\Repository\\MilestonesRepository',
        ]);

        if (isset($container->privates['.service_locator.B11qcrP'])) {
            return $container->privates['.service_locator.B11qcrP'];
        }

        return $container->privates['.service_locator.B11qcrP'] = $instance;
    }
}
