<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Bi3uetuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Bi3uetu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Bi3uetu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'milestonesRepository' => ['privates', 'App\\Repository\\MilestonesRepository', 'getMilestonesRepositoryService', true],
        ], [
            'milestonesRepository' => 'App\\Repository\\MilestonesRepository',
        ]);
    }
}
