<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_6DpIc9sService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.6DpIc9s' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'em' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'produit' => ['privates', '.errored..service_locator.6DpIc9s.App\\Entity\\Produit', NULL, 'Cannot autowire service ".service_locator.6DpIc9s": it needs an instance of "App\\Entity\\Produit" but this type has been excluded in "config/services.yaml".'],
        ], [
            'em' => '?',
            'produit' => 'App\\Entity\\Produit',
        ]);

        if (isset($container->privates['.service_locator.6DpIc9s'])) {
            return $container->privates['.service_locator.6DpIc9s'];
        }

        return $container->privates['.service_locator.6DpIc9s'] = $instance;
    }
}
