<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_GEIp2nWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.GEIp2nW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'execution' => ['privates', '.errored..service_locator.GEIp2nW.App\\Entity\\Execution', NULL, 'Cannot autowire service ".service_locator.GEIp2nW": it needs an instance of "App\\Entity\\Execution" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'execution' => 'App\\Entity\\Execution',
        ]);

        if (isset($container->privates['.service_locator.GEIp2nW'])) {
            return $container->privates['.service_locator.GEIp2nW'];
        }

        return $container->privates['.service_locator.GEIp2nW'] = $instance;
    }
}
