<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_DXCfwtService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.DXCfwt_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        $instance = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'motivation' => ['privates', '.errored..service_locator.DXCfwt_.App\\Entity\\Motivation', NULL, 'Cannot autowire service ".service_locator.DXCfwt_": it needs an instance of "App\\Entity\\Motivation" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'motivation' => 'App\\Entity\\Motivation',
        ]);

        if (isset($container->privates['.service_locator.DXCfwt_'])) {
            return $container->privates['.service_locator.DXCfwt_'];
        }

        return $container->privates['.service_locator.DXCfwt_'] = $instance;
    }
}
