<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_SJHIP6_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.SJHIP6.' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.SJHIP6.'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'phoenixWisdom' => ['privates', '.errored..service_locator.SJHIP6..App\\Entity\\PhoenixWisdom', NULL, 'Cannot autowire service ".service_locator.SJHIP6.": it needs an instance of "App\\Entity\\PhoenixWisdom" but this type has been excluded in "config/services.yaml".'],
        ], [
            'phoenixWisdom' => 'App\\Entity\\PhoenixWisdom',
        ]);
    }
}
