<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_EWeVgEuService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.EWeVgEu' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.EWeVgEu'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'execution' => ['privates', '.errored..service_locator.EWeVgEu.App\\Entity\\Execution', NULL, 'Cannot autowire service ".service_locator.EWeVgEu": it needs an instance of "App\\Entity\\Execution" but this type has been excluded in "config/services.yaml".'],
        ], [
            'execution' => 'App\\Entity\\Execution',
        ]);
    }
}
