<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDeliverTimeMessagesCommandService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Command\DeliverTimeMessagesCommand' shared autowired service.
     *
     * @return \App\Command\DeliverTimeMessagesCommand
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'console'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'Command.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Command'.\DIRECTORY_SEPARATOR.'DeliverTimeMessagesCommand.php';

        $container->privates['App\\Command\\DeliverTimeMessagesCommand'] = $instance = new \App\Command\DeliverTimeMessagesCommand(($container->privates['App\\Repository\\TimeMessageRepository'] ?? $container->load('getTimeMessageRepositoryService')), ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container)));

        $instance->setName('app:deliver-time-messages');
        $instance->setDescription('Mark time messages as delivered when their delivery date is reached');

        return $instance;
    }
}
