<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getExecutionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.EWeVgEu.App\Entity\Execution' shared service.
     *
     * @return \App\Entity\Execution
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.EWeVgEu": it needs an instance of "App\\Entity\\Execution" but this type has been excluded in "config/services.yaml".');
    }
}
