<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMotivationMessagesServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\MotivationMessagesService' shared autowired service.
     *
     * @return \App\Service\MotivationMessagesService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'MotivationMessagesService.php';

        return $container->privates['App\\Service\\MotivationMessagesService'] = new \App\Service\MotivationMessagesService();
    }
}
