<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getMotivationService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.DXCfwt_.App\Entity\Motivation' shared service.
     *
     * @return \App\Entity\Motivation
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.DXCfwt_": it needs an instance of "App\\Entity\\Motivation" but this type has been excluded in "config/services.yaml".');
    }
}
