<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhoenixWisdom2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.hqQD9t0.App\Entity\PhoenixWisdom' shared service.
     *
     * @return \App\Entity\PhoenixWisdom
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.hqQD9t0": it needs an instance of "App\\Entity\\PhoenixWisdom" but this type has been excluded in "config/services.yaml".');
    }
}
