<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhoenixGoal2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.o7u4FJ3.App\Entity\PhoenixGoal' shared service.
     *
     * @return \App\Entity\PhoenixGoal
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.o7u4FJ3": it needs an instance of "App\\Entity\\PhoenixGoal" but this type has been excluded in "config/services.yaml".');
    }
}
