<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getProduit3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.b2NFX8Z.App\Entity\Produit' shared service.
     *
     * @return \App\Entity\Produit
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.b2NFX8Z": it needs an instance of "App\\Entity\\Produit" but this type has been excluded in "config/services.yaml".');
    }
}
