<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhoenixServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\PhoenixService' shared autowired service.
     *
     * @return \App\Service\PhoenixService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'PhoenixService.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ExternalApi'.\DIRECTORY_SEPARATOR.'PhoenixApiManager.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'ExternalApi'.\DIRECTORY_SEPARATOR.'PhoenixAiService.php';

        $a = ($container->services['doctrine.orm.default_entity_manager'] ?? self::getDoctrine_Orm_DefaultEntityManagerService($container));

        if (isset($container->privates['App\\Service\\PhoenixService'])) {
            return $container->privates['App\\Service\\PhoenixService'];
        }
        $b = ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container));

        $instance = new \App\Service\PhoenixService($a, new \App\Service\ExternalApi\PhoenixApiManager(new \App\Service\ExternalApi\PhoenixAiService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), $b), $b), $b);

        if (isset($container->privates['App\\Service\\PhoenixService'])) {
            return $container->privates['App\\Service\\PhoenixService'];
        }

        return $container->privates['App\\Service\\PhoenixService'] = $instance;
    }
}
