<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getPhoenixNetworkService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.VZgwsZd.App\Entity\PhoenixNetwork' shared service.
     *
     * @return \App\Entity\PhoenixNetwork
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.VZgwsZd": it needs an instance of "App\\Entity\\PhoenixNetwork" but this type has been excluded in "config/services.yaml".');
    }
}
