<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getQuestionService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.8ksJNcQ.App\Entity\Question' shared service.
     *
     * @return \App\Entity\Question
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.8ksJNcQ": it needs an instance of "App\\Entity\\Question" but this type has been excluded in "config/services.yaml".');
    }
}
