<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTimeTravelerAiServiceService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Service\TimeTravelerAiService' shared autowired service.
     *
     * @return \App\Service\TimeTravelerAiService
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Service'.\DIRECTORY_SEPARATOR.'TimeTravelerAiService.php';

        return $container->privates['App\\Service\\TimeTravelerAiService'] = new \App\Service\TimeTravelerAiService(($container->privates['.debug.http_client'] ?? self::get_Debug_HttpClientService($container)), ($container->privates['monolog.logger'] ?? self::getMonolog_LoggerService($container)));
    }
}
