<?php

namespace ContainerUVHam0f;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTheme3Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.T.UPThh.App\Entity\Theme' shared service.
     *
     * @return \App\Entity\Theme
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.T.UPThh": it needs an instance of "App\\Entity\\Theme" but this type has been excluded in "config/services.yaml".');
    }
}
