<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXpvCQiR\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXpvCQiR/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXpvCQiR.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXpvCQiR\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXpvCQiR\App_KernelDevDebugContainer([
    'container.build_hash' => 'XpvCQiR',
    'container.build_id' => 'e0f66b74',
    'container.build_time' => 1770390226,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXpvCQiR');
