<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Goal extends \App\Entity\Goal implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'categoryGoa' => [parent::class, 'categoryGoa', null, 16],
        "\0".parent::class."\0".'colorGoa' => [parent::class, 'colorGoa', null, 16],
        "\0".parent::class."\0".'dateDebutGoa' => [parent::class, 'dateDebutGoa', null, 16],
        "\0".parent::class."\0".'dateFinalGoa' => [parent::class, 'dateFinalGoa', null, 16],
        "\0".parent::class."\0".'descriptionGoa' => [parent::class, 'descriptionGoa', null, 16],
        "\0".parent::class."\0".'idGoa' => [parent::class, 'idGoa', null, 16],
        "\0".parent::class."\0".'milestonesGoa' => [parent::class, 'milestonesGoa', null, 16],
        "\0".parent::class."\0".'notesGoa' => [parent::class, 'notesGoa', null, 16],
        "\0".parent::class."\0".'phoenixGoal' => [parent::class, 'phoenixGoal', null, 16],
        "\0".parent::class."\0".'phoenixRebirth' => [parent::class, 'phoenixRebirth', null, 16],
        "\0".parent::class."\0".'priorityGoa' => [parent::class, 'priorityGoa', null, 16],
        "\0".parent::class."\0".'progressGoa' => [parent::class, 'progressGoa', null, 16],
        "\0".parent::class."\0".'statusGoa' => [parent::class, 'statusGoa', null, 16],
        "\0".parent::class."\0".'titleGoa' => [parent::class, 'titleGoa', null, 16],
        'categoryGoa' => [parent::class, 'categoryGoa', null, 16],
        'colorGoa' => [parent::class, 'colorGoa', null, 16],
        'dateDebutGoa' => [parent::class, 'dateDebutGoa', null, 16],
        'dateFinalGoa' => [parent::class, 'dateFinalGoa', null, 16],
        'descriptionGoa' => [parent::class, 'descriptionGoa', null, 16],
        'idGoa' => [parent::class, 'idGoa', null, 16],
        'milestonesGoa' => [parent::class, 'milestonesGoa', null, 16],
        'notesGoa' => [parent::class, 'notesGoa', null, 16],
        'phoenixGoal' => [parent::class, 'phoenixGoal', null, 16],
        'phoenixRebirth' => [parent::class, 'phoenixRebirth', null, 16],
        'priorityGoa' => [parent::class, 'priorityGoa', null, 16],
        'progressGoa' => [parent::class, 'progressGoa', null, 16],
        'statusGoa' => [parent::class, 'statusGoa', null, 16],
        'titleGoa' => [parent::class, 'titleGoa', null, 16],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
